version: '3'
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
  static_website:
    build: ./requirements/bonus/static_website
    image: static_website
    container_name: static_website
    ports:
      - "9090:9090"
    restart: always
    networks:
      - inception
  nodejs:
    build: ./requirements/bonus/nodejs
    image: nodejs
    container_name: nodejs
    ports:
    - "3000:3000"
    restart: always
    networks:
    - inception
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/ylabtaim/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/ylabtaim/data/wordpress
      o: bind
      type: none
networks:
  inception:
    driver: bridge